// <auto-generated />
using DueetAPI.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DueetAPI.Migrations
{
    [DbContext(typeof(DueetContext))]
    [Migration("20230317022206_seedsFruits")]
    partial class seedsFruits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DueetAPI.Models.Fruit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Tax")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("tax");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("Fruit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Maçã fresquinha, direto do pomar para a sua mesa!",
                            Name = "Maça",
                            Tax = 20.3m,
                            Value = 1.45m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Banana madura e doce, perfeita para lanches e sobremesas.",
                            Name = "Banana",
                            Tax = 18.5m,
                            Value = 2.35m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Morangos vermelhos e suculentos, ideais para saladas e doces.",
                            Name = "Morango",
                            Tax = 22.7m,
                            Value = 3.15m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pera fresca e crocante, perfeita para comer ao natural ou em saladas.",
                            Name = "Pera",
                            Tax = 21.2m,
                            Value = 1.95m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Laranjas suculentas e doces, ricas em vitamina C.",
                            Name = "Laranja",
                            Tax = 20.5m,
                            Value = 1.85m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Abacaxi fresco e doce, ideal para sucos e sobremesas.",
                            Name = "Abacaxi",
                            Tax = 26.8m,
                            Value = 4.25m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Uvas maduras e saborosas, perfeitas para comer ao natural ou em sobremesas.",
                            Name = "Uva",
                            Tax = 25.4m,
                            Value = 3.95m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Manga doce e suculenta, ideal para sucos e sobremesas.",
                            Name = "Manga",
                            Tax = 19.8m,
                            Value = 2.75m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Kiwi fresco e ácido, rico em vitamina C e ideal para saladas.",
                            Name = "Kiwi",
                            Tax = 17.6m,
                            Value = 2.15m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Abacaxi tropical, suculento e doce, perfeito para o verão!",
                            Name = "Abacaxi",
                            Tax = 15.8m,
                            Value = 4.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
